FROM python:3.12

# create working directory for docker
WORKDIR /app

# Copy requirements if you have a requirements.txt instead
COPY requirements.txt .
RUN pip install -r requirements.txt

# Add your script
COPY gsla-preprocessing-script.py .

# Set entrypoint for manual overrides
ENTRYPOINT ["python", "gsla-preprocessing-script.py"]

# Keep the container running
CMD ["tail", "-f", "/dev/null"]

# build the image naming 'gsla-py-script'
# docker build -t gsla-py-script .

# run the image, and move generated files to generated-images folder, the files generated by script in /data, then moved to ${PWD}/generated-images.
# docker run  -v "${PWD}/generated-images:/data" gsla-py-script /data