FROM python:3.12

WORKDIR /app

# Install minimal system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy scripts folder and entrypoint
COPY scripts/ ./scripts/
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

# run the image, and move generated files to generated-images folder, the files generated by script in /data, then moved to ${PWD}/generated-images.
# dynamic scripts running based on first argument gsla_processing_script.py or wave_buoys_processing_script.py
# docker run --rm -v "${PWD}/generated-images:/data" ocean-data-processor gsla_processing_script.py --output_base_dir /data --dates 2025-06-19
# docker run --rm -v "${PWD}/generated-images:/data" ocean-data-processor wave_buoys_processing_script.py --output_base_dir /data --dates 2025-06-19


# docker build -t ocean-data-processor .