spring:
  application:
    name: imos-mapbox-server


app:
  storage:
    path: ${user.home}/processed-data
  scheduling:
    taskS3Upload:
      enabled: true

cloud:
  aws:
    region:
      static: ap-southeast-2
    s3:
      bucket: imos-live-test-leslie


